version: '3'

services:

  web:
    build: .
    command: flask run
    ports:
      - "5000:55688"
    # volumes:
    #   - .:/cli_command
    depends_on:
      - db

  db:
    image: mongo:3.6.5
    ports: 
      - "30000:27017"
    environment:
      # provide your credentials here
      - MONGO_INITDB_ROOT_USERNAME=myUserAdmin
      - MONGO_INITDB_ROOT_PASSWORD=abc123
    volumes:
      - "$PWD/mongo_entrypoint.sh:/docker-entrypoint-initdb.d/mongo_entrypoint.sh"
